//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProjectStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Patient_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Practitioner_Time_Start { get; set; }
        public Nullable<System.TimeSpan> Practitioner_Time_End { get; set; }
        public Nullable<System.TimeSpan> Check_In { get; set; }
        public Nullable<System.TimeSpan> Check_Out { get; set; }
        public string Practitioner_ { get; set; }
        public string Prescription { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Time_Slot { get; set; }
        public string Notes { get; set; }
    }
}
