//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProjectStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInformation
    {
        public int Patient_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Social_Security_Number { get; set; }
        public Nullable<bool> Insurance { get; set; }
    }
}
