//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProjectStart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Patient_ID { get; set; }
        public string Prescriptions { get; set; }
        public Nullable<System.DateTime> Added_On { get; set; }
        public string Added_By { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Comments { get; set; }
    }
}
